dist: xenial
sudo: true
language: node_js
node_js:
- node
- 'lts/*'

cache: npm

env:
  global:
    - SOLC_URL='https://github.com/ethereum/solidity/releases/download/v0.6.8/solc-static-linux'
    - SOLC_VERSION='v0.6.8'

before_install:
  - mkdir -p $HOME/.bin
  - export PATH=$PATH:$HOME/.bin
  - ./.travis/download_solc.sh

install:
  - npm install

script:
  - npm run test